// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CheckRssUpdate(arg1:number):Promise<void>;

export function CreateTopic(arg1:string):Promise<dto.TopicResponse>;

export function DeleteTopic(arg1:number):Promise<void>;

export function GetAllRss():Promise<Array<dto.RssItem>>;

export function GetRssDetail(arg1:number):Promise<dto.RssResponse>;

export function GetStandaloneRss():Promise<Array<dto.RssItem>>;

export function GetTopic(arg1:number):Promise<dto.TopicResponse>;

export function GetTopicDetail(arg1:number):Promise<dto.TopicAllInOne>;

export function GetTopics():Promise<Array<dto.TopicResponse>>;

export function Greet(arg1:string):Promise<string>;

export function LinkRssToTopic(arg1:number,arg2:number):Promise<void>;

export function RemoveRss(arg1:number):Promise<void>;

export function SubmitRssUrl(arg1:string,arg2:any):Promise<dto.RssItem>;

export function UnlinkRssFromTopic(arg1:number,arg2:number):Promise<void>;
