// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRssUpdate(arg1) {
  return window['go']['main']['App']['CheckRssUpdate'](arg1);
}

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function GetAllRss() {
  return window['go']['main']['App']['GetAllRss']();
}

export function GetRssDetail(arg1) {
  return window['go']['main']['App']['GetRssDetail'](arg1);
}

export function GetStandaloneRss() {
  return window['go']['main']['App']['GetStandaloneRss']();
}

export function GetTopic(arg1) {
  return window['go']['main']['App']['GetTopic'](arg1);
}

export function GetTopicDetail(arg1) {
  return window['go']['main']['App']['GetTopicDetail'](arg1);
}

export function GetTopics() {
  return window['go']['main']['App']['GetTopics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LinkRssToTopic(arg1, arg2) {
  return window['go']['main']['App']['LinkRssToTopic'](arg1, arg2);
}

export function RemoveRss(arg1) {
  return window['go']['main']['App']['RemoveRss'](arg1);
}

export function SubmitRssUrl(arg1, arg2) {
  return window['go']['main']['App']['SubmitRssUrl'](arg1, arg2);
}

export function UnlinkRssFromTopic(arg1, arg2) {
  return window['go']['main']['App']['UnlinkRssFromTopic'](arg1, arg2);
}
