// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTopic(arg1) {
  return window['go']['main']['App']['CreateTopic'](arg1);
}

export function DeleteTopic(arg1) {
  return window['go']['main']['App']['DeleteTopic'](arg1);
}

export function GetTopic(arg1) {
  return window['go']['main']['App']['GetTopic'](arg1);
}

export function GetTopics() {
  return window['go']['main']['App']['GetTopics']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
