// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';

export function CreateTopic(arg1:string):Promise<dto.TopicResponse>;

export function DeleteTopic(arg1:number):Promise<void>;

export function GetTopic(arg1:number):Promise<dto.TopicResponse>;

export function GetTopics():Promise<Array<dto.TopicResponse>>;

export function Greet(arg1:string):Promise<string>;
